# runtime: python39
# entrypoint: gunicorn -b :$PORT main:app

# instance_class: F2
# automatic_scaling:
  # target_cpu_utilization: 0.65
  # target_throughput_utilization: 0.75
  # max_instances: 5

# env_variables:
  # ENV: "production"
  
runtime: python312
env: flex

entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  operating_system: "ubuntu22"

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.65

env_variables:
  ENV: "production"


